// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcfeayauhdcjqdmbsjlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZmVheWF1aGRjanFkbWJzamxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjA4NzEsImV4cCI6MjA2ODk5Njg3MX0.1gAu1QE8pCm48jwizW6NUyHsIm430Xi1HrzU0LVe7q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});